### ISSUE TITLE
Changing the default fileformat (MP4) of the recorded meeting in Jibri to another format

### ISSUE THREAD

**Issue by WilfriedBieseman** [jitsi/jibri#266]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by WilfriedBieseman** [comment]
I installed Jitsi Meet with Jibri. All seems to work well, but I can't open the generated file, wich is a MP4. I remember having the choise of video-format while installing but I can't find a config to change the format from mp4 to f.e. WMV. Uninstalling Jibri and reïnstlling it doesn't solve the problem. Is there anyone who knows a meens to change de video-format of an already installed Jibri?

**Comment by aaronkvanmeerten** [comment]
This is better as a community forum post rather than a github issue.  Currently jibri records only to mp4 file formats.  This is via parameters passed into ffmpeg, so it's possible that alternate parameters could change what format it writes, but that's currently not supported.  We'd welcome any contributions for such a feature, so long as it was behind configuration parameters.
