### ISSUE TITLE
Permission denied when trying to run jibriselenium.py

### ISSUE THREAD

**Issue by subsub** [jitsi/jibri#37]
I've got this error when trying to run this command: `DISPLAY=:0 ./jibriselenium.py -u https://my.testing.conference`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./jibriselenium.py", line 324, in <module>
    js = JibriSeleniumDriver(URL,token,displayname=displayname,email=email,pjsua_flag=pjsua_flag)
  File "./jibriselenium.py", line 69, in __init__
    self.initDriver()
  File "./jibriselenium.py", line 83, in initDriver
    self.driver = webdriver.Chrome(chrome_options=options, desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 61, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f48d7c4a630>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 162, in __del__
    self.stop()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 134, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'
```

I am on Jibri user. I tried to change the /usr/bin/chromedriver owner to jibri but still get the error.
Any ideas how to fix this?
Thank you

**Comment by subsub** [comment]
Turns out the executable path inside webdriver.py is pointing to wrong path. The installation guide tells to put chromedriver inside /usr/bin, while the executable_path actually pointing to /home/jibri/jibri-xmpp-client/chromedriver, so I manually change the executable_path="/usr/bin/chromedriver/chromedriver"

**Comment by asinorum** [comment]
@subsub I'm stuck on the same permission error. I'm not a linux expert, please, how did you do to "manually change the executable path"?

**Comment by aaronkvanmeerten** [comment]
Please ensure that the chromedriver executable has the +x flag set.  The default installation of jibri does not require the executable_path be set, simply that the chromedriver executable be available in the system path, and the executable bit set.

sudo chmod +x /usr/bin/chromedriver

**Comment by asinorum** [comment]
Hi Aaron
Thanks for the response, please, correct me if im wrong, i think the
permissions are set.

ls -l /usr/bin/chromedriver
total 7496
-rwxr-xr-x 1 jibri root 7673176 Aug 10 14:18 chromedriver


Jorge Vertiz.

2017-08-18 10:05 GMT-05:00 Aaron van Meerten <notifications@github.com>:

**Comment by aaronkvanmeerten** [comment]
Yes this looks correct.  In our deployments we do not specify the chromedriver path anyway, and it all works as expected.

You may also look into whether your chrome binary itself is set up properly.

In our deployment we set config.json to have the following property:

  "chrome_binary_path": "/usr/bin/google-chrome”,

Maybe ensure that your chrome binary path is correct as well, and has +x permissions?

If not, please email your config.json (minus any passwords) so we can review and see if anything else pops out.

-Aaron

**Comment by asinorum** [comment]
I don't know if understood you properly, i'm kind a lost right now, but
looking in to my config.json file does not have any "chrome_binary_path"
declaration at all, it look very much like this file
https://github.com/jitsi/jibri/blob/master/config.json but with my
passwords and stuff.
but looking in the app.py file there is a chrome_binary_path=None, thats
what you mean.

Jorge Vertiz.

2017-08-18 10:34 GMT-05:00 Aaron van Meerten <notifications@github.com>:

> Yes this looks correct. In our deployments we do not specify the
> chromedriver path anyway, and it all works as expected.
>
> You may also look into whether your chrome binary itself is set up
> properly.
>
> In our deployment we set config.json to have the following property:
>
> "chrome_binary_path": "/usr/bin/google-chrome”,
>
> Maybe ensure that your chrome binary path is correct as well, and has +x
> permissions?
>
> If not, please email your config.json (minus any passwords) so we can
> review and see if anything else pops out.
>
> -Aaron
>

**Comment by aaronkvanmeerten** [comment]
Can you try adding that property to config.json and see if you still get the problem?  If this solves the issue, then maybe we need to include this value in to the example config.json file in the repo.

Cheers,

-Aaron

**Comment by asinorum** [comment]
i'll give a try on add that path to config.json, but what i've already done
is add the binary path to this line
https://github.com/jitsi/jibri/blob/master/jibri-xmpp-client/jibriselenium.py#L22
but didnt works.

Jorge Vertiz.

2017-08-18 11:01 GMT-05:00 Aaron van Meerten <notifications@github.com>:

> Can you try adding that property to config.json and see if you still get
> the problem? If this solves the issue, then maybe we need to include this
> value in to the example config.json file in the repo.
>
> Cheers,
>
> -Aaron
>
>

**Comment by asinorum** [comment]
ok, i did add this line  "chrome_binary_path":"/usr/bin/chromedriver”, to
the config.jason, i use that path because of this
https://github.com/jitsi/jibri#miscellaneous-required-tools

Still the same result:

su - jibri
$ cd /home/jibri/jibri-xmpp-client/
$ DISPLAY=:0 ./jibriselenium.py -u https://my.domain.com/test
Initializing Driver
Traceback (most recent call last):
  File
"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py",
line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./jibriselenium.py", line 324, in <module>
    js =
JibriSeleniumDriver(URL,token,displayname=displayname,email=email,pjsua_flag=pjsua_flag)
  File "./jibriselenium.py", line 69, in __init__
    self.initDriver()
  File "./jibriselenium.py", line 83, in initDriver
    self.driver = webdriver.Chrome(chrome_options=options,
desired_capabilities=desired_capabilities)
  File
"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py",
line 61, in __init__
    self.service.start()
  File
"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py",
line 74, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver'
executable may have wrong permissions. Please see
https://sites.google.com/a/chromium.org/chromedriver/home

Exception ignored in: <bound method Service.__del__ of
<selenium.webdriver.chrome.service.Service object at 0x7fb33313d5f8>>
Traceback (most recent call last):
  File
"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py",
line 162, in __del__
    self.stop()
  File
"/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py",
line 134, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

also, i dont know if related, when i try this:


   - sudo su - jibri
   - cd /home/jibri/scritps
   - ./launch_recording.sh null null null STREAM_KEY

works fine

regrads

Jorge Vertiz.

2017-08-18 11:20 GMT-05:00 Jorge Vértiz <asinorum@gmail.com>:

> i'll give a try on add that path to config.json, but what i've already
> done is add the binary path to this line https://github.com/jitsi/
> jibri/blob/master/jibri-xmpp-client/jibriselenium.py#L22 but didnt works.
>
> Jorge Vertiz.
>
> 2017-08-18 11:01 GMT-05:00 Aaron van Meerten <notifications@github.com>:
>
>> Can you try adding that property to config.json and see if you still get
>> the problem? If this solves the issue, then maybe we need to include this
>> value in to the example config.json file in the repo.
>>
>> Cheers,
>>
>> -Aaron
>>
>>

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!
