### ISSUE TITLE
jibri - recording and save in server without youtube stream

### ISSUE THREAD

**Issue by mail2niaz** [jitsi/jibri#43]
Hi
When i click on recording icon, it asks me for stream key. Is it not possible to record meeting and save in server without youtube streaming ?

**Comment by krakatoa** [comment]
You can always replace the $STREAM var in this line with a disk path where Ffmpeg will stream to.

**Comment by aaronkvanmeerten** [comment]
We have recently added some basic support in lib-jitsi-meet and jicofo for recording to a  file.  This is intended to be combined with some sort of custom publishing script which would copy the file to a more permanent location after recording is complete, and then report it somewhere (maybe an email or a chat message to a chat server, the sky is the limit).  This isn't fully completed but the skeleton of it is now in the master branch.

**Comment by animer3009** [comment]
can you describe what to do to use record only function?

**Comment by ctscobra** [comment]
So how is this done , what needs to be changed?
I lost days trying to get recording working before I concluded that it simply does not work.
I don't need streaming , need regular record to a file. Tests from jibri cli worked fine , i can record audio and video without issues like that but need an option to call it from UI where only Streaming is available.

**Comment by aaronkvanmeerten** [comment]
I would very much recommend using the latest java-based jibri from our debian respository.  It's easier to use and is much more reliable about getting connected.  I'm going to close this issue, but please open a new one if you run into any problems with the new java-based jibri!

**Comment by vincentwlau** [comment]
@aaronkvanmeerten Won't it be more useful if the recorded mp4 file path is passed as a parameter to the custom publishing script?  If only the folder path is available, the script won't know which file to be uploaded and it may need a mechanism to avoid concurrent uploads.
I also learned that there was a protocol change between jibri and jicofo on 2018-05-15.  The latest java-based jibri requires the latest jicofo.  Otherwise, build your own jibri based on 2018-05-09 source codes.  This version seems working fine with a stable jicofo release.  Specifying recordingType: 'jibre_file' in the /etc/jitsi/meet/your-domain-config.js will do the file recording.

**Comment by bbaldino** [comment]
@vincentwlau jibri [now](https://github.com/jitsi/jibri/commit/db8134245b5c3458e4d31e6690c11d46aa5c65bc) creates a new directory for each recording, so when the script gets that directory passed, it can assume all files in that directory are for that recording and should be handled.
