### ISSUE TITLE
There is no record button

### ISSUE THREAD

**Issue by animer3009** [jitsi/jibri#47]
Hi. 

I have no record button in jitsi-meet i have only stream button.
How to make record button or auto start recording? also how make record without youtube stream.

How to make multi room recording? I knew that one jibri can record one room, but how to make recording servers pool and recording automatisation?

Where find documentation about how to do all this.

Thanks early for answers.

**Comment by aaronkvanmeerten** [comment]
The record to a file feature has not made it to jitsi-meet yet.  Jibri supports it and the associated transports in jicofo and libjitsimeet are in, but the final user experience is still being designed and built.  There is no plans to make auto-recording a feature at the moment.

As for the multi room recordings, you will want to create a pool of jibri servers using any method you desire.  Simply set up a jibri by hand, then create an image out of it.  Then launch this image in an autoscaling group or however your virtualization environment provides server pool functionality.  A slight configuration change per jibri is needed to give them each a unique nickname, but otherwise they should be basically the same.  You can run as many or as few of these as you wish, and if you'd like to add the ability to launch new jibris automatically, you can use the statistics provided by the jibri rest interface to determine how many jibris are recording.  Simply throw this statistic as a metric into your cloud provider of choice, and then use this metric to control your autoscaling rules.  None of this is documented as it is outside the scope of the jibri project.

Alternately, there is a PR open to allow multiple jibri processes running on the same instance.  Your mileage may vary with this approach, as jibri does require constant CPU utilization to work with good performance.
