### ISSUE TITLE
Jibri launch_recording.sh connect to youtube but not showing  conference video

### ISSUE THREAD

**Issue by cheelibrahmaiah** [jitsi/jibri#61]
Hi All,

I have setup JIBRI same as given instructions [Here](https://github.com/jitsi/jibri), i tested using start-ffmpeg.sh working fine, it's created new filename.flv file but it consisting only connecting message, no video visible, same for launch_recording.sh also connected youtube live but same connecting message broadcast.

Appreciate your help. 
Thanks.

**Comment by Ark74** [comment]
If you used the manual script to broadcast then that's what you should see.
You should need to use the stream button to stream you conference.

I was about to ask the same, because I got stuck at this point too.
All tests pass manually but can't start streaming from inside the room.

**Comment by cheelibrahmaiah** [comment]
I have setup New JITSI-MEET stable version and JIBRI is Working with
YouTube Live Stream.
But my requirement is need save separate file, any suggestions please
update here.

**Comment by Ark74** [comment]
> But my requirement is need save separate file

Sorry I don't understand this. 

I have got it to work too, thanks to a @gricuk recommendation.
I'd like to do more testing

**Comment by Ark74** [comment]
Got you previous comment after reading like 10 times :nerd_face:  

As the way jibri works, i believe it would be easier to setup a screen recorder (i.e. vokoscreen) on any of the hosts. I read somewhere that someone made a fork of jidesha to record files or something like it. You would need to look it up.

Or download the recorded file from YouTube xD, just kidding.

Cheers

**Comment by aaronkvanmeerten** [comment]
There is some functionality in Jibri itself to support recording to a file instead of streaming to youtube.  This feature is in its infancy.  The basic idea is that a slightly separate message is sent to Jibri from Jicofo, indicating that a recording should be created.  Then at the end of the meeting, a script is run (finalize_recording.sh) which is intended to be modified to upload your recording to the destination of your choice.  You could cp it somewhere or upload it to cloud storage, etc.  This script is also intended to notify whatever other endpoints might be interested in the new location of the recording.  This is all meant to be customized by the end user, so the example script simply walks through all the recorded files from the meeting and removes them.

This feature is not fully instrumented across lib-jitsi-meet and jitsi-meet UI elements, so it may not be as easy to use as some of the basic jibri features until that subsequent work is completed.

**Comment by cheelibrahmaiah** [comment]
Thanks Everyone...:)
**JIBRI Works for me**, We can record the JITSI MEET Conference to a file(.mp4)  by Running jibriselenium.py and start-ffmpeg.sh one by one.
Here we are changed the Jibriselenium user session time limit 60sec to infinite. so we can able capture entire  JITSI MEET Conference is stored into a seperate file, once recording is completed we are calling stop_recording.sh to stop recording.

**Comment by krisalay** [comment]
@cheelibrahmaiah 
Hello, 
The `jibriselenium.py` script works fine for me. But when I execute `start-ffmpeg.sh` script it shows nothing. Can you help me with the code?
