### ISSUE TITLE
Stuck on Starting Live Stream...

### ISSUE THREAD

**Issue by dmitriy-01** [jitsi/jibri#76]
Hi all,

I got it working till the input of a stream key. But after entering it, Jitsi meeting room shows "Starting Live Stream..." window and after 1.5 minutes shows "Live stream failed to start" message.

Everything works fine if I do this selenium test with the same stream key:
`./launch_recording.sh null null null STREAM_KEY`
I can see that stream on YouTube.

But can't launch it in actual meeting room. Also I noticed these jicofo logs:

`Jicofo 2018-03-29 19:15:19.222 INFO: [36] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().169 Jibri: thebrewery@conference.join.learnformula.com/jibri-5643991639678753 available: false`

`Jicofo 2018-03-29 19:16:49.174 SEVERE: [73] org.jitsi.jicofo.recording.jibri.JibriSession.log() Jibri pending timeout! room1@conference.join.learnformula.com`

Note that first message shows that "Jibri: ... available: false" by some reason, however all processes are started fine: jibri-xorg, jibri-icewm and jibri-xmpp.

Any way to fix or debug this further?

Thanks.

**Comment by aaronkvanmeerten** [comment]
We'd need to see the logs from jibri itself.  The jicofo logs are actually accurate.  When you first send a start command to the jibri via jicofo, it replies to the jicofo and sends a "busy" status, which results in jicofo reporting the jibri as unavailable (since it is now engaged in a recording operation).  Then after 90 seconds jibri hasn't reported successful connection, so jicofo times it out and cancels.

The jibri logs may show that selenium failed to start, or that you didn't pass the audio checks, or that ffmpeg failed to start.  Those will be your best bet to post here for more details on what to fix.

**Comment by websquared** [comment]
Thanks @aaronkvanmeerten 

Could you tell me where can I find those jibri logs? 
I can see jicofo.log and jvb.log under /var/log/jitsi/ folder but not jibri

**Comment by websquared** [comment]
However if I run `check_audio.sh` script it gives this output:

```
Recording raw data '/tmp/jibri-audio_check.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Hardware PCM card 0 'Loopback' device 1 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 22052
  period_size  : 5513
  period_time  : 125011
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 5513
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 22052
  silence_threshold: 0
  silence_size : 0
  boundary     : 6207086186423386112
  appl_ptr     : 0
  hw_ptr       : 0
```
Which seems to be fine.

Is there a way to debug or test audio?

**Comment by websquared** [comment]
@aaronkvanmeerten 
Ok, I figured that I have a problem even with manual audio check:
```
arecord -d 1 -D hw:0,1 -v -f cd -t raw /tmp/jibri-audio_check.wav
xxd /tmp/jibri-audio_check.wav | grep -v ' 0000 ' | wc -l
```
Giving me `0`

However when I run `lsmod | grep snd_aloop`, it's showing this:
```
snd_aloop              24576  0
snd_pcm               106496  1 snd_aloop
snd                    81920  6 snd_aloop,snd_timer,snd_pcm,snd_seq,snd_rawmidi,snd_seq_device
```

Not sure if it's expected output. I use clean Amazon EC2 Ubuntu 16.04 instance and followed all the instructions, step-by-step.

Any help to debug this further appreciated! Thanks!

**Comment by saydulk** [comment]
did you complete things to do after install ubuntu

**Comment by websquared** [comment]
Yes, even tried to do a fresh installation on new EC2 Ubuntu instance (just had to change boot kernel from aws to generic linux to install snd-aloop). Followed every step of the instructions. Spent many hours on installing, setting it up and testing and still exactly the same issue - everything in Jitsi works except Live Stream. And this time I used the latest Jitsi night build instead of stable.

Even hired a System Administrator to look specifically into this issue - still nothing, he couldn't help as well :)

Very frustrating, especially that I don't even know how to debug that at this point or what to do next to fix it!

**Comment by ultraboby** [comment]
I have the same issue Ubuntu 16.04 (VMware VM)
