### ISSUE TITLE
Recording unavailable jibri 1.3.49-1

### ISSUE THREAD

**Issue by kybi** [jitsi/jibri#96]
Hi,

I setup jibri with jitsi on ubuntu 16.04. When press button 'Start recording' in UI show notification "Recording unavailable". I don't see any error in console log or any errors in 

```
 /var/log/jitsi/jvb.log 
 /var/log/jitsi/jicofo.log
 /var/log/jitsi/jibri/log.*.txt 
 /var/log/prosody/prosody.err
 /var/log/prosody/prosody.log
```
**Package version**
```
Package: jibri
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 40407
Maintainer: dev@jitsi.org
Architecture: all
Version: 1.3.49-1
Depends: default-jre-headless | java8-runtime-headless | java8-runtime, ffmpeg, curl, alsa-utils, icewm, xdotool, xserver-xorg-input-void, xserver-xorg-video-dummy
Conffiles:
 /etc/jitsi/jibri/asoundrc e4733108912bebab8d3ce0e1e9974919
 /etc/jitsi/jibri/config.json 2cb1cec7e5a91dc3d4e61687eb247198
 /etc/jitsi/jibri/icewm.preferences ae2b364f1c7768a397577ee9b7908279
 /etc/jitsi/jibri/logging.properties 7fee26395b5c28b008c2b4e2a9a77fed
 /etc/jitsi/jibri/xorg-video-dummy.conf 095543e2c3474de2064d9aeb2b6b1e0d
 /etc/systemd/system/jibri-icewm.service 721957db4bbc274ef8f2c812d3dcad86
 /etc/systemd/system/jibri-xorg.service 4c7e64ae79137f0d89c18714ca29b078
 /etc/systemd/system/jibri.service da7bbcc581aa1e14ec14b490e7cd32e2
```
```
Package: jitsi-meet
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 11
Maintainer: Jitsi Team <dev@jitsi.org>
Architecture: all
Version: 1.0.2988-1
Depends: jitsi-videobridge (= 1055-1), jicofo (= 1.0-405-1), jitsi-meet-web (= 1.0.2740-1), jitsi-meet-web-config (= 1.0.2740-1), jitsi-meet-prosody (= 1.0.2740-1)
```
```
Package: prosody
Status: install ok installed
Priority: extra
Section: net
Installed-Size: 1226
Maintainer: Matthew James Wild <mwild1@gmail.com>
Architecture: amd64
Multi-Arch: foreign
Version: 0.10.0-1~xenial4
Replaces: prosody, prosody-xmpp-server
Provides: prosody, prosody-xmpp-server, xmpp-server
Depends: lsb-base, lua5.1, lua5.1-expat, lua5.1-filesystem, lua5.1-socket, openssl, ssl-cert, libc6 (>= 2.14), libidn11 (>= 1.13), libssl1.0.0 (>= 1.0.0)
Pre-Depends: adduser
Recommends: lua-sec (>= 0.5), lua-bitop, ca-certificates
Suggests: lua-event, lua-dbi-mysql, lua-dbi-postgresql, lua-dbi-sqlite3, lua-zlib
Conflicts: prosody, prosody-xmpp-server
Conffiles:
 /etc/init.d/prosody 1b177ee4d46bbbf3dcc17b215f9f54eb
 /etc/logrotate.d/prosody 8ac1509c06cac587a53e5b24c9742bc9
 /etc/prosody/certs/Makefile 6d314b75e66b04520f31aec6f85dc69e
 /etc/prosody/certs/localhost.cnf 37af2ca0908d1ad5393bd71ff27abbdd
 /etc/prosody/certs/openssl.cnf d551929eea6e16914ab17c68459c9868
 /etc/prosody/prosody.cfg.lua bcd4deb8429858f50cbec3f00d41250a
 /etc/prosody/README 0449cb3bc6efd160f9621c1f2503572d obsolete
 /etc/prosody/migrator.cfg.lua 8578cf0a80d036b5505f59fd27054d47 obsolete
 /etc/prosody/conf.avail/example.com.cfg.lua e4d047b795e1e062844dd7f14e45b44f obsolete
 /etc/prosody/conf.avail/localhost.cfg.lua c5005c1f57bd8a44ae572320ace8227b obsolete
```
**Enable recording** in jitsi meet
```
    enableRecording: true,
    // Type for recording: one of jibri or jirecon.
    recordingType: 'jibri_file',
    hiddenDomain: 'recorder.au.meet.domain.com',
```

**configs** in zip file
```
/etc/jitsi/jibri/config.json -> jibri-config.json
/etc/jitsi/jicofo/config -> jicofo-config
/etc/jitsi/jicofo/sip-communicator.properties -> jicofo-sip-communicator.properties
/etc/jitsi/meet/au.meet.domain.com-config.js -> jitsi-meet-au.meet.domain.com-config.js
/etc/prosody/conf.d/au.meet.domain.com.cfg.lua -> prosody-au.meet.domain.com.cfg.lua
```
[jibri-configs.zip](https://github.com/jitsi/jibri/files/1969948/jibri-configs.zip)

How I can debug problem ? 

Thank you very much for help

**Comment by bbaldino** [comment]
Did you add the settings in the [Jicofo config](https://github.com/jitsi/jibri#jicofo) file?  Can you give us your Jicofo logs?

**Comment by kybi** [comment]
Yes, all config is in jibri-configs.zip

root@au:~# cat /etc/jitsi/jicofo/sip-communicator.properties
org.jitsi.jicofo.jibri.BREWERY=JitsiBrewery@conference.au.meet.domain.com
org.jitsi.jicofo.jibri.PENDING_TIMEOUT=90

[jicofo.log.zip](https://github.com/jitsi/jibri/files/1973432/jicofo.log.zip)

**Comment by bbaldino** [comment]
In your jibri config you have:

```
            "control_muc": {
                "domain": "conference.au.meet.domain.com",
                "room_name": "JibriBrewery",
                "nickname": "jibri"
            },
```

But in the Jicofo config you have:
```
org.jitsi.jicofo.jibri.BREWERY=JitsiBrewery@conference.au.meet.domain.com
```
The room names here should match (`JibriBrewery` vs `JitsiBrewery`)

**Comment by kybi** [comment]
thank you. I change and restart server, but still "Recording unavailable".

```
root@au:/etc# ack-grep JibriBrewery
jitsi/jicofo/sip-communicator.properties
3:org.jitsi.jicofo.jibri.BREWERY=JibriBrewery@conference.au.meet.domian.com

jitsi/jibri/config.json
34:                "room_name": "JibriBrewery",
```
new jicofo.log  
[jicofo.log.zip](https://github.com/jitsi/jibri/files/1975250/jicofo.log.zip)

**Comment by bbaldino** [comment]
Jicofo still isn't seeing Jibri in the muc:

Jicofo 2018-05-05 02:49:47.565 INFO: [58]
org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publish new JIBRI
status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri'
status='undefined'/> in: dev@conference.au.meet.datakonnect.com

Can you start both things fresh (Jicofo then Jibri) and paste their logs?

**Comment by kybi** [comment]
fresh log jicofo and jibri
[jicofo-jibri-logs.zip](https://github.com/jitsi/jibri/files/1975333/jicofo-jibri-logs.zip)

**Comment by bbaldino** [comment]
Hm, something is up with Jibri here; there should be more logs than that.
Can you paste your entire jibri config json?  (Make sure to change anything
potentially sensitive).

**Comment by kybi** [comment]
```
{
    "recording_directory":"/var/tmp/recordings",
    "finalize_recording_script_path": "/home/jibri/jibri/resources/finalize_recording.sh",
    "xmpp_environments": [
        {
            "name": "AU MEET DK",
            "xmpp_server_hosts": [
                "au.meet.domain.com"
            ],
            "xmpp_domain": "au.meet.domain.com",
            "control_login": {
                "domain": "auth.au.meet.domain.com",
                "username": "jibri",
                "password": "XXXXXXXX"
            },
            "control_muc": {
                "domain": "conference.au.meet.domain.com",
                "room_name": "JibriBrewery",
                "nickname": "jibri"
            },
            "call_login": {
                "domain": "recorder.au.meet.domian.com",
                "username": "recorder",
                "password": "XXXXXXXX"
            },
            "room_jid_domain_string_to_strip_from_start": "conference.",
            "usage_timeout": "0"
        }
    ]
}
```

**Comment by bbaldino** [comment]
Hmm, works fine for me.  I get this output from Jibri when it starts up:

2018-05-04 10:44:28.123 INFO: [1] org.jitsi.jibri.Main.main() Using config
file /Users/bbaldino/jitsi/jibri-new/config-test.json
2018-05-04 10:44:29.248 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed
config:
JibriConfig(recordingDirectory=/var/tmp/recordings,
finalizeRecordingScriptPath=/home/jibri/jibri/resources/finalize_recording.sh,
xmppEnvironments=[XmppEnvironmentConfig(name=AU MEET DK, xmppServerHosts=[
au.meet.domain.com], xmppDomain=au.meet.domain.com,
controlLogin=XmppCredentials(domain=auth.au.meet.domain.com,
username=jibri, password=XXXXXXXX), controlMuc=XmppMuc(domain=
conference.au.meet.domain.com, roomName=JibriBrewery, nickname=jibri),
sipControlMuc=null, callLogin=XmppCredentials(domain=
recorder.au.meet.domian.com, username=recorder, password=XXXXXXXX),
stripFromRoomDomain=conference., usageTimeoutMins=0,
trustAllXmppCerts=true)])
2018-05-04 10:44:29.322:INFO::main: Logging initialized @1935ms
2018-05-04 10:44:29.370:WARN:oejsh.ContextHandler:main:
o.e.j.s.ServletContextHandler@63798ca7{/,null,null} contextPath ends with /*
2018-05-04 10:44:29.370:WARN:oejsh.ContextHandler:main: Empty contextPath
2018-05-04 10:44:29.375:INFO:oejs.Server:main: jetty-9.2.10.v20150310
2018-05-04 10:44:29.821 WARNING: [1]
org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A
provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in
SERVER runtime does not implement any provider interfaces applicable in the
SERVER runtime. Due to constraint configuration problems the provider
org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored.
2018-05-04 10:44:29.951:INFO:oejsh.ContextHandler:main: Started
o.e.j.s.ServletContextHandler@63798ca7{/,null,AVAILABLE}
2018-05-04 10:44:29.982:INFO:oejs.ServerConnector:main: Started
ServerConnector@27abb83e{HTTP/1.1}{0.0.0.0:3333}
2018-05-04 10:44:29.982:INFO:oejs.Server:main: Started @2597ms
2018-05-04 10:44:30.172 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start()
Connecting to xmpp environment on au.meet.domain.com with config
XmppEnvironmentConfig(name=AU MEET DK, xmppServerHosts=[au.meet.domain.com],
xmppDomain=au.meet.domain.com, controlLogin=XmppCredentials(domain=
auth.au.meet.domain.com, username=jibri, password=XXXXXXXX),
controlMuc=XmppMuc(domain=conference.au.meet.domain.com,
roomName=JibriBrewery, nickname=jibri), sipControlMuc=null,
callLogin=XmppCredentials(domain=recorder.au.meet.domian.com,
username=recorder, password=XXXXXXXX), stripFromRoomDomain=conference.,
usageTimeoutMins=0, trustAllXmppCerts=true)
2018-05-04 10:44:30.184 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start()
The trustAllXmppCerts config is enabled for this domain, all XMPP server
provided certificates will be accepted
2018-05-04 10:44:30.346 SEVERE: [1]
org.jitsi.jibri.api.xmpp.XmppApi.error() Error connecting to xmpp
environment: org.jivesoftware.smack.SmackException$ConnectionException: The
following addresses failed: 'au.meet.domain.com:5222' failed because:
au.meet.domain.com/66.96.162.92 exception: java.net.ConnectException:
Connection refused (Connection refused)
2018-05-04 10:44:30.348:WARN:oejsh.ContextHandler:main:
o.e.j.s.ServletContextHandler@6dcd5639{/,null,null} contextPath ends with /*
2018-05-04 10:44:30.348:WARN:oejsh.ContextHandler:main: Empty contextPath
2018-05-04 10:44:30.348:INFO:oejs.Server:main: jetty-9.2.10.v20150310
2018-05-04 10:44:30.383 WARNING: [1]
org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A
provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does
not implement any provider interfaces applicable in the SERVER runtime. Due
to constraint configuration problems the provider
org.jitsi.jibri.api.http.HttpApi will be ignored.
2018-05-04 10:44:30.423:INFO:oejsh.ContextHandler:main: Started
o.e.j.s.ServletContextHandler@6dcd5639{/,null,AVAILABLE}
2018-05-04 10:44:30.423:INFO:oejs.ServerConnector:main: Started
ServerConnector@23811a09{HTTP/1.1}{0.0.0.0:2222}
2018-05-04 10:44:30.424:INFO:oejs.Server:main: Started @3038ms
2018-05-04 10:45:00.220 WARNING: [23]
org.jivesoftware.smackx.ping.PingManager.pingServerIfNecessary()
XMPPConnection was not authenticated


It could be that one of the things you omitted from your config when you
pasted it here is tripping up the parser?  Try with the same thing you
pasted here and see if that makes any difference.  Also I wanted to make
sure it's not a logging config thing, what does your logging.properties
look like? Are you passing it to Jibri like:
-Djava.util.logging.config.file=/path/to/lib/logging.properties

**Comment by bbaldino** [comment]
I don't think the recording token is hooked up to anything right now, so you can just enter whatever you want.  @aaronkvanmeerten what is the recording token thing for?  Is there an option to disable that prompt?

**Comment by aaronkvanmeerten** [comment]
That sounds like the value for config.js in jitsi-meet is incorrect.  What version of jitsi-meet are you running?  What is the contents of your config.js?  It should be recording_type:"jibri", and you should be using newish version of jitsi meet.  If you see the "recording token" value, it means you have misconfigured jitsi meet somehow, or are running an old version of it.

**Comment by kybi** [comment]
```
Package: jitsi-meet
Version: 1.0.2988-1
Depends: jitsi-videobridge (= 1055-1), jicofo (= 1.0-405-1), jitsi-meet-web (= 1.0.2740-1), jitsi-meet-web-config (= 1.0.2740-1), jitsi-meet-prosody (= 1.0.2740-1)
```
I want to record to file
```
recordingType: 'jibri_file',
```

**Comment by bbaldino** [comment]
Yeah, @virtuacoplenny looked up 'token' and it was from an old version of recording.  We'll have that fixed in meet somewhat soon probably.  In the meantime, you can just put whatever you want in there and it should work.

**Comment by kybi** [comment]
jibri log when press 'Start recording'
```
2018-05-05 04:56:53.109 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq() Received JibriIq <iq to='jibri@auth.au.meet.domain.com/c8901cc5-18c5-4c70-a838-c6f4b6e2438f' from='jibribrewery@conference.au.meet.domain.com/focus' id='amlicmlAYXV0aC5hdS5tZWV0LmRhdGFrb25uZWN0LmNvbS9jODkwMWNjNS0xOGM1LTRjNzAtYTgzOC1jNmY0YjZlMjQzOGYAa0Rwa0UtNTAzMABb7P5hXZjhgFMtCx1u6Op+' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' room='dev@conference.au.meet.domain.com'/></iq> from environment AU MEET DK
2018-05-05 04:56:53.110 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Received start request
2018-05-05 04:56:53.112 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq() Sending 'pending' response to start IQ
2018-05-05 04:56:53.113 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.run() Starting service
2018-05-05 04:56:53.116 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.handleStartService() Parsed call url info: CallUrlInfo(baseUrl=https://au.meet.domain.com, callName=dev)
2018-05-05 04:56:53.117 INFO: [38] org.jitsi.jibri.JibriManager.startFileRecording() Starting a file recording with params: FileRecordingRequestParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://au.meet.domain.com, callName=dev)), callLoginParams=XmppCredentials(domain=recorder.au.meet.domain.com, username=recorder, password=tango656)) finalize script path: /home/jibri/jibri/resources/finalize_recording.sh and recordings directory: /var/tmp/recordings
Starting ChromeDriver 2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb) on port 15294
Only local connections are allowed.
```
UI show 
```Recording waiting for a member to join...```

join another member

jibri log, some problem with chrome
```
2018-05-05 04:57:53.519 SEVERE: [38] org.jitsi.jibri.api.xmpp.XmppApi.error() Error in startService task: org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-122-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.07 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'au.meet.domain.com', ip: '139.99.172.233', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-122-generic', java.version: '1.8.0_162'
Driver info: driver.version: ChromeDriver
2018-05-05 04:57:53.520 INFO: [38] org.jitsi.jibri.api.xmpp.XmppApi.run() Sending start service response iq: <iq to='jibribrewery@conference.au.meet.domain.com/focus' id='XZ22F-26' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='failed'/></iq>
2018-05-05 04:57:53.523 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq() Received JibriIq <iq to='jibri@auth.au.meet.domain.com/c8901cc5-18c5-4c70-a838-c6f4b6e2438f' from='jibribrewery@conference.au.meet.domain.com/focus' id='amlicmlAYXV0aC5hdS5tZWV0LmRhdGFrb25uZWN0LmNvbS9jODkwMWNjNS0xOGM1LTRjNzAtYTgzOC1jNmY0YjZlMjQzOGYAa0Rwa0UtNTA4MwBb7P5hXZjhgFMtCx1u6Op+' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='stop'/></iq> from environment AU MEET DK
2018-05-05 04:57:53.524 INFO: [24] org.jitsi.jibri.JibriManager.stopService() Stopping the current service
2018-05-05 04:57:53.524 INFO: [24] org.jitsi.jibri.api.xmpp.XmppApi.invoke() Jibri reports its status is now idle, publishing presence to connection AU MEET DK
```

any idea ??

**Comment by kybi** [comment]
@bbaldino 
google-chrome-stable is already the newest version (66.0.3359.139-1).

**Comment by bbaldino** [comment]
We don't have much insight into chrome failures.  We do enable verbose chrome logs, so might be something there.  Info about chrome logs is here: https://www.chromium.org/for-testers/enable-logging

**Comment by bbaldino** [comment]
Jibri already enables the chrome logs: https://github.com/jitsi/jibri/blob/master/src/main/kotlin/org/jitsi/jibri/selenium/JibriSelenium.kt#L133

I just don't know offhand where they get written to (that's what that page I linked will tell you).

**Comment by kybi** [comment]
/tmp/chromedriver.log

```
[1525460213.454][INFO]: COMMAND InitSession {
   "capabilities": {
      "desiredCapabilities": {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix" ],
            "extensions": [  ]
         },
         "loggingPrefs": {
            "driver": "ALL"
         }
      },
      "firstMatch": [ {
         "browserName": "chrome",
         "goog:chromeOptions": {
            "args": [ "--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix" ],
            "extensions": [  ]
         }
      } ]
   },
   "desiredCapabilities": {
      "browserName": "chrome",
      "goog:chromeOptions": {
         "args": [ "--use-fake-ui-for-media-stream", "--start-maximized", "--kiosk", "--enabled", "--enable-logging", "--vmodule=*=3", "--disable-infobars", "--alsa-output-device=plug:amix" ],
         "extensions": [  ]
      },
      "loggingPrefs": {
         "driver": "ALL"
      }
   }
}
[1525460213.454][INFO]: Populating Preferences file: {
   "alternate_error_pages": {
      "enabled": false
   },
   "autofill": {
      "enabled": false
   },
   "browser": {
      "check_default_browser": false
   },
   "distribution": {
      "import_bookmarks": false,
      "import_history": false,
      "import_search_engine": false,
      "make_chrome_default_for_user": false,
      "skip_first_run_ui": true
   },
   "dns_prefetching": {
      "enabled": false
   },
   "profile": {
      "content_settings": {
         "pattern_pairs": {
            "https://*,*": {
               "media-stream": {
                  "audio": "Default",
                  "video": "Default"
               }
            }
         }
      },
      "default_content_setting_values": {
         "geolocation": 1
      },
      "default_content_settings": {
         "geolocation": 1,
         "mouselock": 1,
         "notifications": 1,
         "popups": 1,
         "ppapi-broker": 1
      },
      "password_manager_enabled": false
   },
   "safebrowsing": {
      "enabled": false
   },
   "search": {
      "suggest_enabled": false
   },
   "translate": {
      "enabled": false
   }
}
[1525460213.454][INFO]: Populating Local State file: {
   "background_mode": {
      "enabled": false
   },
   "ssl": {
      "rev_checking": {
         "enabled": false
      }
   }
}
[1525460213.455][INFO]: Launching chrome: /usr/bin/google-chrome --alsa-output-device=plug:amix --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --enabled --force-fieldtrials=SiteIsolationExtensions/Control --ignore-certificate-errors --kiosk --load-extension=/tmp/.org.chromium.Chromium.VOcr0m/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12051 --start-maximized --test-type=webdriver --use-fake-ui-for-media-stream --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.YLGVi1 --vmodule=*=3 data:,
[1525460273.490][INFO]: RESPONSE InitSession unknown error: Chrome failed to start: exited abnormally
```

**Comment by bbaldino** [comment]
Those are the chromedriver logs, not the chrome logs.  The chrome logs get written to the chrome user directory somewhere (details are in that link).

Are you running Jibri from source?  What OS is Jibri running on?

**Comment by kybi** [comment]
ubuntu os jibri 
```
 deb https://download.jitsi.org unstable/
```

**Comment by kybi** [comment]
jitsi meet stable

```deb https://download.jitsi.org stable/
```

**Comment by Ark74** [comment]
The wiki suggest to use jibri (deb) unstable via repository, that will upgrade all the running applications to unstable, not only jibri.
Is that the desired behavior for this new jibri backend?

Cheers!

**Comment by kybi** [comment]
When upgrade to latest jibri and jitsi meet, recording now working ;) 
Thank you for help.

 I will close issue.

**Comment by krisalay** [comment]
@kybi 
Which version of jibri and jitsi-meet are you using for the recording?

**Comment by kybi** [comment]
Hi @krisalay 

```
Package: jibri
Version: 2.0.51-1
```
```
Package: jitsi-meet
Version: 1.0.3078-1
Depends: jitsi-videobridge (= 1057-1), jicofo (= 1.0-414-1), jitsi-meet-web (= 1.0.2821-1), jitsi-meet-web-config (= 1.0.2821-1), jitsi-meet-prosody (= 1.0.2821-1)
```
